server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: NotificationService

  # env 파일 내의 환경변수를 불러오는 설정
  config:
    import: optional:file:.env

  # 데이터베이스(MySQL) 연결 설정 (notification_db)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA(Hibernate) 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# Firebase FCM 설정 연동 (커스텀 속성)
firebase:
  config:
    path: ${FIREBASE_CONFIG_PATH}
